#!/bin/sh

# Install Python virtual envrionment
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
cd "$SCRIPT_DIR"
. ./venv.incl

# remove old venv
. $RHUB/shell/lib.sh
# generated by `uuidgen`
SAFE_CODE="61214A82-33E6-4C33-812A-EB092003EA5C"
saferemove "$VENV" "$SAFE_CODE"

# create new venv
mkdir -p "$VENV"
touch "$VENV/$SAFE_CODE"
python3 -m venv "$VENV"
. "$VENV"/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools
python3 -m pip install -r ./requirements.txt

# make python3-dev (or python-dev for Python 2), libxml2-dev libxslt1-dev
# zlib1g-dev are installed







